@include('components.formparts.facilityMain')
@include('components.formparts.bathingForm')
@include('components.formparts.facilityPayment')
@include('components.formparts.facilityEvents')
@include('components.formparts.facilityRestaurant')